version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./eotc-helper/tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command:
      bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/eotc-helper
    ports:
      - "3001:3000"
    depends_on:
      - db
